# Generated by Django 5.0 on 2023-12-19 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('account_age', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.URLField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('pets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets_api.pet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
